sonar.projectKey=devops-k8s-project
sonar.projectName=devops-k8s-project
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src,frontend/src
sonar.tests=backend/test
sonar.test.inclusions=backend/test/**/*.test.js

sonar.exclusions=**/node_modules/**,frontend/dist/**,**/coverage/**
