apiVersion: v1
kind: Service
metadata:
  name: testjs
  namespace: default
  labels:
    app: testjs
spec:
  type: NodePort
  selector:
    app: testjs
  ports:
    - port: 5000
      targetPort: 3001
      nodePort: 32004
      protocol: TCP
